"""customer table

Revision ID: 6a1946b5c207
Revises: 7b75c301ea14
Create Date: 2022-05-10 10:12:55.768975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a1946b5c207'
down_revision = '7b75c301ea14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=55), nullable=False),
    sa.Column('last_name', sa.String(length=55), nullable=False),
    sa.Column('display_name', sa.String(length=55), nullable=False),
    sa.Column('street', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=255), nullable=False),
    sa.Column('postal_code', sa.String(length=255), nullable=False),
    sa.Column('lat', sa.String(length=255), nullable=True),
    sa.Column('long', sa.String(length=255), nullable=True),
    sa.Column('mobile_number', sa.String(length=255), nullable=False),
    sa.Column('home_number', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('work_number', sa.String(length=255), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('businesses', sa.Column('country', sa.String(length=255), nullable=True))
    op.add_column('businesses', sa.Column('lat', sa.String(length=255), nullable=True))
    op.add_column('businesses', sa.Column('long', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'long')
    op.drop_column('businesses', 'lat')
    op.drop_column('businesses', 'country')
    op.drop_table('customers')
    # ### end Alembic commands ###
