"""jointable

Revision ID: 0602396fd1f0
Revises: d999daa30c9d
Create Date: 2022-05-10 11:50:54.273555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0602396fd1f0'
down_revision = 'd999daa30c9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobServices',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('service_id', 'job_id')
    )
    op.drop_constraint('jobs_service_id_fkey', 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'service_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('jobs_service_id_fkey', 'jobs', 'services', ['service_id'], ['id'])
    op.drop_table('jobServices')
    # ### end Alembic commands ###
