"""update usertable

Revision ID: 899b0fc2041f
Revises: ffdc0a98111c
Create Date: 2022-05-10 08:37:43.637130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '899b0fc2041f'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=55), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=55), nullable=False))
    op.add_column('users', sa.Column('role', sa.String(length=55), nullable=False))
    op.add_column('users', sa.Column('date_joined', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('color', sa.String(length=55), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'color')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'date_joined')
    op.drop_column('users', 'role')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
