"""tablesnewnew

Revision ID: 5fe459592aa8
Revises: 7a7a6c1bebc9
Create Date: 2022-05-11 14:04:12.000964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fe459592aa8'
down_revision = '7a7a6c1bebc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('business_id', sa.Integer(), nullable=False))
    op.drop_constraint('users_user_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'businesses', ['business_id'], ['id'])
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_user_id_fkey', 'users', 'businesses', ['user_id'], ['id'])
    op.drop_column('users', 'business_id')
    # ### end Alembic commands ###
