"""updated items and customer nulls

Revision ID: 6b0387480614
Revises: 2e7bb29f2877
Create Date: 2022-08-21 16:38:07.880414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b0387480614'
down_revision = '2e7bb29f2877'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'first_name',
               existing_type=sa.VARCHAR(length=55),
               nullable=True)
    op.alter_column('customers', 'last_name',
               existing_type=sa.VARCHAR(length=55),
               nullable=True)
    op.alter_column('customers', 'mobile_number',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('customers', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('customers', 'note',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('items', sa.Column('business_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'items', 'businesses', ['business_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_column('items', 'business_id')
    op.alter_column('customers', 'note',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('customers', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('customers', 'mobile_number',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('customers', 'last_name',
               existing_type=sa.VARCHAR(length=55),
               nullable=False)
    op.alter_column('customers', 'first_name',
               existing_type=sa.VARCHAR(length=55),
               nullable=False)
    # ### end Alembic commands ###
