"""tablesnew

Revision ID: 7a7a6c1bebc9
Revises: 16d58455949d
Create Date: 2022-05-11 14:03:44.581758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a7a6c1bebc9'
down_revision = '16d58455949d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'businesses', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###
