"""empty message

Revision ID: d20f4feffb0f
Revises: d4a659ee7087
Create Date: 2022-05-17 21:50:52.355643

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd20f4feffb0f'
down_revision = 'd4a659ee7087'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('from_date_time', sa.DateTime(), nullable=False))
    op.add_column('jobs', sa.Column('to_date_time', sa.DateTime(), nullable=False))
    op.drop_column('jobs', 'to_date')
    op.drop_column('jobs', 'to_time')
    op.drop_column('jobs', 'from_date')
    op.drop_column('jobs', 'from_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('from_time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('from_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('to_time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('to_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('jobs', 'to_date_time')
    op.drop_column('jobs', 'from_date_time')
    # ### end Alembic commands ###
